### ISSUE TITLE
Sign installers

### ISSUE THREAD

**Issue by eXeLearningProject** [exelearning/exelearning#24]
Sign Mac installers and create an account to sign the Windows installers too.

**Comment by erseco** [comment]
Adding more details about Windows code signing using [Microsoft Trusted Signing](https://techcommunity.microsoft.com/blog/microsoft-security-blog/trusted-signing-is-in-public-preview/4103457).

Right now, we are decoding a `.pfx` file from GitHub Secrets and passing it to `electron-builder` using `WIN_CSC_LINK` and `WIN_CSC_KEY_PASSWORD`. This works, but it means we must store a binary secret and rotate it manually when it expires.

With Trusted Signing we can:

* Avoid storing the certificate in the repository or as a secret.
* Let the pipeline request a signing certificate dynamically using Azure Key Vault and Microsoft’s CA.
* Use Microsoft’s GitHub Action (`azure/trusted-signing-action`) to sign our `.exe` or `.msi` artifacts before publishing.

### Example change in the GitHub Actions workflow

```yaml
      # Sign artifacts using Microsoft Trusted Signing
      - name: Sign Windows artifacts
        if: matrix.os == 'windows-latest'
        uses: azure/trusted-signing-action@v1
        with:
          endpoint: ${{ secrets.TRUSTED_SIGNING_ENDPOINT }}
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          files: 'dist/*.exe;dist/*.msi'
          description: 'eXeLearning Windows Installer'
          publisher-name: 'eXeLearning Project'
```

This step would replace the `Decode Windows certificate` step and remove the need for `WIN_CSC_LINK` and `WIN_CSC_KEY_PASSWORD`.

### electron-builder configuration

In `package.json`, we keep `"signAndEditExecutable": true` so that `electron-builder` produces unsigned binaries, then we sign them as a separate step using the action above. If we prefer to let `electron-builder` handle signing directly, we could provide a custom `sign` script that calls `signtool` with Azure-issued certificate parameters, but using the GitHub Action is easier and integrates well with CI.

References:

* [Microsoft Trusted Signing](https://techcommunity.microsoft.com/blog/microsoft-security-blog/trusted-signing-is-in-public-preview/4103457)
* [electron-builder Windows code signing docs](https://www.electron.build/code-signing-win)

This way, the pipeline remains secure and automated:

* macOS: uses Apple certificate from GitHub Actions secure keychain
* Windows: uses Trusted Signing with ephemeral credentials
* Linux: no signing needed
